In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os


In [2]:
df=pd.read_csv(r'E:\Batch 52- Day10\Salary_Data.csv')
df

YearsExperience  Salary
0               1.1   39343
1               1.3   46205
2               1.5   37731
3               2.0   43525
4               2.2   39891
5               2.9   56642
6               3.0   60150
7               3.2   54445
8               3.2   64445
9               3.7   57189
10              3.9   63218
11              4.0   55794
12              4.0   56957
13              4.1   57081
14              4.5   61111
15              4.9   67938
16              5.1   66029
17              5.3   83088
18              5.9   81363
19              6.0   93940
20              6.8   91738
21              7.1   98273
22              7.9  101302
23              8.2  113812
24              8.7  109431
25              9.0  105582
26              9.5  116969
27              9.6  112635
28             10.3  122391
29             10.5  121872

In [18]:
x=df.iloc[:,:-1].values
y=df.iloc[:,1].values

In [142]:
from sklearn.model_selection import train_test_split
x_train, x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

In [143]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(x_train, y_train)

LinearRegression()

In [28]:
x_test,y_test

(array([[10.5],
        [ 4.5],
        [ 7.9],
        [ 9.6],
        [ 5.3],
        [ 2.9]]),
 array([121872,  61111, 101302, 112635,  83088,  56642], dtype=int64))

In [136]:
y_pred= reg.predict(x_test)
print (y_pred)

[126237.38501393  68341.33518643 101149.09675535 117552.9775398
  76060.80849676  52902.38856576]


In [133]:
a=y_pred-y_test
x_test

array([[10.5],
       [ 4.5],
       [ 7.9],
       [ 9.6],
       [ 5.3],
       [ 2.9]])

In [137]:
from sklearn.metrics import r2_score
print ('Coefficient', reg.coef_)
print ('Intercept', reg.intercept_)
r2_score(y_test,y_pred)

Coefficient [9649.34163792]
Intercept 24919.29781580408


0.9564526464653216

In [100]:
from sklearn.metrics import r2_score
print ('Coefficient', reg.coef_)
print ('Intercept', reg.intercept_)
r2_score(y_test,b)

Coefficient [9649.34163792]
Intercept 24919.29781580408


0.9350141507522469

In [134]:
print(reg.predict([[4.5]]))

[68341.33518643]


In [3]:
os.getcwd()

'C:\\Users\\Brain Hacker\\Documents\\Python Jupiter'

In [129]:
df=pd. read_excel(r'E:\Batch 52- Day9\Data Preprocessing Data File.xlsx')

In [138]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1:].values
a=df.iloc[:,:-1].values
b=df.iloc[:,-1:].values
df

Country   Age   Salary  Purchased 
0   France   44.0  72000.0         No
1    Spain   27.0  48000.0        Yes
2  Germany    NaN  54000.0         No
3    Spain   39.0      NaN         No
4  Germany    NaN  64000.0        Yes
5   France   35.0  58000.0        Yes
6    Spain   39.0  52000.0         No
7   France   48.0      NaN        Yes
8  Germany   50.0  83000.0         No
9   France   37.0  67000.0        Yes

In [139]:
from sklearn.impute import SimpleImputer as si
imp=si(missing_values=np.nan, strategy='mean')
imp=imp.fit(x[:,1:3])
x[:,1:3]=imp.transform(x[:,1:3])
x

array([['France ', 44.0, 72000.0],
       ['Spain ', 27.0, 48000.0],
       ['Germany ', 39.875, 54000.0],
       ['Spain ', 39.0, 62250.0],
       ['Germany ', 39.875, 64000.0],
       ['France ', 35.0, 58000.0],
       ['Spain ', 39.0, 52000.0],
       ['France ', 48.0, 62250.0],
       ['Germany ', 50.0, 83000.0],
       ['France ', 37.0, 67000.0]], dtype=object)

In [141]:
from sklearn.compose import ColumnTransformer as ct
from sklearn.preprocessing import OneHotEncoder
ct=ct(transformers=[('EN',OneHotEncoder(),[0])],remainder='passthrough')
x=np.array(ct.fit_transform(x))
pd.DataFrame(x)

0  1  2       3      4
0  1  0  0      44  72000
1  0  0  1      27  48000
2  0  1  0  39.875  54000
3  0  0  1      39  62250
4  0  1  0  39.875  64000
5  1  0  0      35  58000
6  0  0  1      39  52000
7  1  0  0      48  62250
8  0  1  0      50  83000
9  1  0  0      37  67000

In [113]:
from sklearn.preprocessing import LabelEncoder as le
en=le()
y=en.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [142]:
from sklearn.preprocessing import StandardScaler as sc
st_sc=sc()
std_x=st_sc.fit_transform(x)
pd.DataFrame(std_x)

0         1         2         3         4
0  1.224745 -0.654654 -0.654654  0.664912  1.002707
1 -0.816497 -0.654654  1.527525 -2.075331 -1.465494
2 -0.816497  1.527525 -0.654654  0.000000 -0.848444
3 -0.816497 -0.654654  1.527525 -0.141042  0.000000
4 -0.816497  1.527525 -0.654654  0.000000  0.179973
5  1.224745 -0.654654 -0.654654 -0.785805 -0.437077
6 -0.816497 -0.654654  1.527525 -0.141042 -1.054127
7  1.224745 -0.654654 -0.654654  1.309675  0.000000
8 -0.816497  1.527525 -0.654654  1.632056  2.133965
9  1.224745 -0.654654 -0.654654 -0.463423  0.488498

In [143]:
from sklearn.preprocessing import MinMaxScaler as mms
mm=mms()
mms_x=mm.fit_transform(x)
print(pd.DataFrame(mms_x))

     0    1    2         3         4
0  1.0  0.0  0.0  0.739130  0.685714
1  0.0  0.0  1.0  0.000000  0.000000
2  0.0  1.0  0.0  0.559783  0.171429
3  0.0  0.0  1.0  0.521739  0.407143
4  0.0  1.0  0.0  0.559783  0.457143
5  1.0  0.0  0.0  0.347826  0.285714
6  0.0  0.0  1.0  0.521739  0.114286
7  1.0  0.0  0.0  0.913043  0.407143
8  0.0  1.0  0.0  1.000000  1.000000
9  1.0  0.0  0.0  0.434783  0.542857


In [118]:
from sklearn.preprocessing import MinMaxScaler as mms
print(pd.DataFrame(mms().fit_transform(x)))

     0    1    2         3         4
0  1.0  0.0  0.0  0.739130  0.685714
1  0.0  0.0  1.0  0.000000  0.000000
2  0.0  1.0  0.0  0.521739  0.171429
3  0.0  0.0  1.0  0.521739  0.407143
4  0.0  1.0  0.0  0.521739  0.457143
5  1.0  0.0  0.0  0.347826  0.285714
6  0.0  0.0  1.0  0.521739  0.114286
7  1.0  0.0  0.0  0.913043  0.407143
8  0.0  1.0  0.0  1.000000  1.000000
9  1.0  0.0  0.0  0.434783  0.542857


In [136]:
from sklearn.preprocessing import StandardScaler as sc
pd.DataFrame(sc().fit_transform(x))
x

array([[0.0, 1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 1.0, 0.0, 39.875, 54000.0],
       [1.0, 0.0, 0.0, 1.0, 39.0, 62250.0],
       [1.0, 0.0, 1.0, 0.0, 39.875, 64000.0],
       [0.0, 1.0, 0.0, 0.0, 35.0, 58000.0],
       [1.0, 0.0, 0.0, 1.0, 39.0, 52000.0],
       [0.0, 1.0, 0.0, 0.0, 48.0, 62250.0],
       [1.0, 0.0, 1.0, 0.0, 50.0, 83000.0],
       [0.0, 1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [101]:
from sklearn.preprocessing import Normalizer as NML
nm=NML()
nm_x=nm.fit_transform(x)
print(pd.DataFrame(nm_x))

          0         1         2         3         4    5
0  0.000000  0.000014  0.000000  0.000000  0.000611  1.0
1  0.000021  0.000000  0.000000  0.000021  0.000562  1.0
2  0.000019  0.000000  0.000019  0.000000  0.000722  1.0
3  0.000016  0.000000  0.000000  0.000016  0.000627  1.0
4  0.000016  0.000000  0.000016  0.000000  0.000609  1.0
5  0.000000  0.000017  0.000000  0.000000  0.000603  1.0
6  0.000019  0.000000  0.000000  0.000019  0.000750  1.0
7  0.000000  0.000016  0.000000  0.000000  0.000771  1.0
8  0.000012  0.000000  0.000012  0.000000  0.000602  1.0
9  0.000000  0.000015  0.000000  0.000000  0.000552  1.0


array([[    0,     1,     0,     0,    44, 72000],
       [    1,     0,     0,     1,    27, 48000],
       [    1,     0,     1,     0,    39, 54000],
       [    1,     0,     0,     1,    39, 62250],
       [    1,     0,     1,     0,    39, 64000],
       [    0,     1,     0,     0,    35, 58000],
       [    1,     0,     0,     1,    39, 52000],
       [    0,     1,     0,     0,    48, 62250],
       [    1,     0,     1,     0,    50, 83000],
       [    0,     1,     0,     0,    37, 67000]])

In [102]:
from sklearn.preprocessing import Normalizer as NML
print(pd.DataFrame(NML().fit_transform(x)))

          0         1         2         3         4    5
0  0.000000  0.000014  0.000000  0.000000  0.000611  1.0
1  0.000021  0.000000  0.000000  0.000021  0.000562  1.0
2  0.000019  0.000000  0.000019  0.000000  0.000722  1.0
3  0.000016  0.000000  0.000000  0.000016  0.000627  1.0
4  0.000016  0.000000  0.000016  0.000000  0.000609  1.0
5  0.000000  0.000017  0.000000  0.000000  0.000603  1.0
6  0.000019  0.000000  0.000000  0.000019  0.000750  1.0
7  0.000000  0.000016  0.000000  0.000000  0.000771  1.0
8  0.000012  0.000000  0.000012  0.000000  0.000602  1.0
9  0.000000  0.000015  0.000000  0.000000  0.000552  1.0


array([[    1,     0,     0,    44, 72000],
       [    0,     0,     1,    27, 48000],
       [    0,     1,     0,    39, 54000],
       [    0,     0,     1,    39, 62250],
       [    0,     1,     0,    39, 64000],
       [    1,     0,     0,    35, 58000],
       [    0,     0,     1,    39, 52000],
       [    1,     0,     0,    48, 62250],
       [    0,     1,     0,    50, 83000],
       [    1,     0,     0,    37, 67000]])

In [ ]:
from sklearn.preprocessing import LabelEncoder as le
en=le()
a[:,0]=en.fit_transform(a[:,0])
print(a)