In [57]:
import numpy as np
arr=np.array([-2147483648])
print(arr)
print(arr.shape)
print(arr.size)
print(arr.itemsize)

[-2147483648]
(1,)
1
4


In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr.reshape(5,2)
print(arr)


In [73]:
#2^32/2-1 =2147483647 4 Bytes positive -2^32/32 =-2147483648 4bytes Negative
a=np.array([-2147483648])
b=np.array([2147483647])
c=np.array([-2147483649])
d=np.array([2147483648])
e=np.array([2147483647,2147483647,2147483647,2147483647])
f=np.array([2147483648,2147483647,2147483647,2147483647])
print(a.itemsize)
print(b.itemsize)
print(c.itemsize)
print(d.itemsize)
print(e.itemsize)
print(e[0].itemsize)
print(f.itemsize)
print(f[0].itemsize)


4
4
8
8
4
4
8
8


In [80]:
list1,list2=[1,2,3,4,5,6,7,8,9],[10,11,12,13,14,16,17,18,19]
a=np.array([[list1],[list2]])
print(a)

[[[ 1  2  3  4  5  6  7  8  9]]

 [[10 11 12 13 14 16 17 18 19]]]


In [98]:
list1=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,16,17,18,19,20]
a=np.array(list1)
print(a.reshape(5,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 16]
 [17 18 19 20]]


In [100]:
list1=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
a=np.array(list1)
print(a.reshape(2,2,5))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]


In [101]:
list1=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
a=np.array(list1)
print(a.reshape(2,5,2))

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


In [118]:
b=np.arange(30)
print(b.shape)
b.reshape(3,5,2)
print(b)



(30,)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [124]:
list1=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
a=np.array(list1)
print(a)
b=a.copy()
b[0]=100
print(b)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [134]:
c=np.ones((5,5))*5
b=c.astype(int)
print(b)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [152]:
list1=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
x=np.array(list1)
print(x)
print(x[::-1])
print(x[3:7])
print(x[-11:-1])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]
[3 4 5 6]
[ 9 10 11 12 13 14 15 16 17 18]


In [151]:
y=np.array([[1,2,3,3,4],[11,12,13,13,14]])
print(y)
print(y[1][0:2])
print(y[0][::-1])
print(y[1][1])

[[ 1  2  3  3  4]
 [11 12 13 13 14]]
[11 12]
[4 3 3 2 1]
12


In [154]:
arr1=np.array([[1,2,3,3,4,6],[11,12,13,13,14,16]])
print (arr1)
print (arr1.shape)
print (arr1.ndim)
print (arr1.itemsize)
print (arr1.dtype)
print (arr1.size)
print (arr1.min())
print (arr1.max())
print (arr1.sum())
print (np.sqrt(arr1))
print (np.std(arr1))


[[ 1  2  3  3  4  6]
 [11 12 13 13 14 16]]
(2, 6)
2
4
int32
12
1
16
98
[[1.         1.41421356 1.73205081 1.73205081 2.         2.44948974]
 [3.31662479 3.46410162 3.60555128 3.60555128 3.74165739 4.        ]]
5.241395064505463


In [5]:
import numpy as np
x = np.arange(10,1,-1)
x=x[np.array([3,3,-3,8])]
x[b[0:]]

NameError: name 'b' is not defined