In [1]:
import numpy as np,pandas as pd,os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import r2_score
df=pd.read_csv(r'50_Startups.csv')
df

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42  California  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68    New York  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95  California  146121.95
11  100671.96        91790.61        249744.55     Florida  144259.40
12   93863.75       127320.38        249839.44  California  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57    New York  124266.90
19   86419.70       153514.11             0.00     Florida  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26  California  110352.25
23   67532.53       105751.03        304768.73  California  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07    New York  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24    New York   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81    New York   96778.92
34   46426.07       157693.92        210797.67     Florida   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82    New York   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67     Florida   78239.91
41   27892.92        84710.77        164470.71  California   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [2]:
x=df.iloc[:,:4].values
y=df.iloc[:,-1:].values

In [70]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('EN',OneHotEncoder(),[3])],remainder='passthrough')
print(ct)
nx=ct.fit_transform(x)
fx=nx

ColumnTransformer(remainder='passthrough',
                  transformers=[('EN', OneHotEncoder(), [3])])


In [27]:
from sklearn.preprocessing import LabelEncoder as le
x[:,3]=le().fit_transform(x[:,3])

array([[165349.2, 136897.8, 471784.1, 2],
       [162597.7, 151377.59, 443898.53, 0],
       [153441.51, 101145.55, 407934.54, 1],
       [144372.41, 118671.85, 383199.62, 2],
       [142107.34, 91391.77, 366168.42, 0],
       [131876.9, 99814.71, 362861.36, 2],
       [134615.46, 147198.87, 127716.82, 0],
       [130298.13, 145530.06, 323876.68, 2],
       [120542.52, 148718.95, 311613.29, 2],
       [123334.88, 108679.17, 304981.62, 0],
       [101913.08, 110594.11, 229160.95, 0],
       [100671.96, 91790.61, 249744.55, 1],
       [93863.75, 127320.38, 249839.44, 0],
       [91992.39, 135495.07, 252664.93, 0],
       [119943.24, 156547.42, 256512.92, 1],
       [114523.61, 122616.84, 261776.23, 2],
       [78013.11, 121597.55, 264346.06, 0],
       [94657.16, 145077.58, 282574.31, 2],
       [91749.16, 114175.79, 294919.57, 2],
       [86419.7, 153514.11, 0.0, 1],
       [76253.86, 113867.3, 298664.47, 0],
       [78389.47, 153773.43, 299737.29, 2],
       [73994.56, 122782.75, 30331

In [28]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=45)

In [29]:
from sklearn.linear_model import LinearRegression as lrm
rg=lrm().fit(x_train,y_train)
r2_score(y_test,rg.predict(x_test))

0.9831525126962402

In [7]:
print(y_test.ravel())

[ 42559.73 155752.6  191050.39 149759.96 156991.12 105733.54 134307.35
  89949.14 192261.83 122776.86]


In [8]:
rg.predict(x_test).ravel()

array([ 46347.26770088, 160365.27179344, 181273.48836564, 154377.97605384,
       163826.05439569, 110832.84208999, 127270.93915949,  89308.33018497,
       192991.37362198, 114221.13469514])

In [9]:
y_test-rg.predict(x_test)

array([[-3787.53770088],
       [-4612.67179344],
       [ 9776.90163436],
       [-4618.01605384],
       [-6834.93439569],
       [-5099.30208999],
       [ 7036.41084051],
       [  640.80981503],
       [ -729.54362198],
       [ 8555.72530486]])

In [10]:
r2_score(y,rg.predict(nx))

0.9503090448283839

In [11]:
rg.coef_ 

array([[-9.63380327e+01, -4.78905377e+02,  5.75243410e+02,
         7.94383696e-01, -2.17815130e-02,  3.10605080e-02]])

In [12]:
df

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42  California  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68    New York  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95  California  146121.95
11  100671.96        91790.61        249744.55     Florida  144259.40
12   93863.75       127320.38        249839.44  California  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57    New York  124266.90
19   86419.70       153514.11             0.00     Florida  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26  California  110352.25
23   67532.53       105751.03        304768.73  California  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07    New York  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24    New York   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81    New York   96778.92
34   46426.07       157693.92        210797.67     Florida   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82    New York   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67     Florida   78239.91
41   27892.92        84710.77        164470.71  California   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [16]:
a=pd.DataFrame(nx,columns=['California','Florina','New York','R&D Spend','Administration','Marketing Spend'])
b=pd.DataFrame(y,columns=['Profit'])
c=pd.DataFrame(rg.predict(nx),columns=['Predicted Profit'])
d=pd.DataFrame(y-rg.predict(nx),columns=['Difference Profit vs Predicted Profit'])
r=pd.concat([a,b,c,d],axis=1)
r.to_csv('Predicted_salary',index=False)

In [14]:
c=nx.astype(np.float64)
import statsmodels.api as sm
reg_ols = sm.OLS (endog = y, exog =c)
reg_ols = reg_ols.fit()
print (reg_ols.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     171.2
Date:                Thu, 17 Jun 2021   Prob (F-statistic):           1.14e-27
Time:                        10:09:41   Log-Likelihood:                -525.19
No. Observations:                  50   AIC:                             1062.
Df Residuals:                      44   BIC:                             1074.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1          5.062e+04   6806.869      7.436      0.0

In [71]:
c=fx[:,[3,4,5]].astype(np.float64)
import statsmodels.api as sm
reg_ols = sm.OLS (endog = y, exog =c)
reg_ols = reg_ols.fit()
print (reg_ols.summary())

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.987
Model:                            OLS   Adj. R-squared (uncentered):              0.987
Method:                 Least Squares   F-statistic:                              1232.
Date:                Thu, 17 Jun 2021   Prob (F-statistic):                    1.17e-44
Time:                        12:15:23   Log-Likelihood:                         -545.82
No. Observations:                  50   AIC:                                      1098.
Df Residuals:                      47   BIC:                                      1103.
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

In [30]:
from sklearn.linear_model import LinearRegression as lg
pg=lg().fit(c,y)
r2_score(y,pg.predict(c))

0.9465353160804392

In [47]:
c=x[:,:3].astype(np.float64)
import statsmodels.api as sm
reg_ols = sm.OLS (endog = y, exog =c)
reg_ols = reg_ols.fit()
print (reg_ols.summary())

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.987
Model:                            OLS   Adj. R-squared (uncentered):              0.987
Method:                 Least Squares   F-statistic:                              1232.
Date:                Thu, 17 Jun 2021   Prob (F-statistic):                    1.17e-44
Time:                        10:25:07   Log-Likelihood:                         -545.82
No. Observations:                  50   AIC:                                      1098.
Df Residuals:                      47   BIC:                                      1103.
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

In [66]:
c=nx[:,[4]].astype(np.float64)
import statsmodels.api as sm
reg_ols = sm.OLS (endog = y, exog =c)
reg_ols = reg_ols.fit()
print (reg_ols.summary())

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.871
Model:                            OLS   Adj. R-squared (uncentered):              0.868
Method:                 Least Squares   F-statistic:                              331.2
Date:                Thu, 17 Jun 2021   Prob (F-statistic):                    1.92e-23
Time:                        12:09:34   Log-Likelihood:                         -604.03
No. Observations:                  50   AIC:                                      1210.
Df Residuals:                      49   BIC:                                      1212.
Df Model:                           1                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------